// ── AgricFi MVP — Farm Data ──
const FARMS = [
  {
    id: 'AGF-OGN-001',
    name: 'Maize Farm',
    location: 'Ogun State',
    state: 'Ogun',
    crop: 'Maize',
    size: 50,
    coords: '6.8672° N, 3.4432° E',
    serial: 'AGF-OGN-001-2026',
    status: 'live',
    roi: { min: 18, max: 25 },
    target: 40000,
    raised: 28800,
    investors: 18,
    cycle: 'Q3 2026',
    iot: true,
    kyc: true,
    featured: true,
    nftId: '#001',
    color: 'green',
    mapColor: 'rgba(0,255,135',
    description: 'IoT-enabled maize cultivation across 50 verified hectares in Ogun State. Soil analysis confirmed optimal pH levels. Harvest projected Q3 2026.'
  },
  {
    id: 'AGF-KEB-002',
    name: 'Rice Farm',
    location: 'Kebbi State',
    state: 'Kebbi',
    crop: 'Rice',
    size: 80,
    coords: '12.4539° N, 4.1975° E',
    serial: 'AGF-KEB-002-2026',
    status: 'filling',
    roi: { min: 20, max: 28 },
    target: 65000,
    raised: 29250,
    investors: 16,
    cycle: 'Q4 2026',
    iot: true,
    kyc: true,
    featured: true,
    nftId: '#002',
    color: 'gold',
    mapColor: 'rgba(240,192,64',
    description: 'Large-scale rice cultivation in Nigeria\'s primary rice belt. 80 hectares of verified farmland with full irrigation infrastructure.'
  },
  {
    id: 'AGF-BNU-003',
    name: 'Cassava Farm',
    location: 'Benue State',
    state: 'Benue',
    crop: 'Cassava',
    size: 30,
    coords: '7.3376° N, 8.8953° E',
    serial: 'AGF-BNU-003-2026',
    status: 'soon',
    roi: { min: 15, max: 22 },
    target: 35000,
    raised: 0,
    investors: 0,
    cycle: 'TBA 2026',
    iot: false,
    kyc: false,
    featured: true,
    nftId: '#003',
    color: 'muted',
    mapColor: 'rgba(150,150,255',
    description: 'Cassava cultivation on fertile Benue soil. KYC verification in progress. Whitelist now open for early investors.'
  },
  {
    id: 'AGF-KAN-004',
    name: 'Soybean Estate',
    location: 'Kano State',
    state: 'Kano',
    crop: 'Soybean',
    size: 120,
    coords: '11.9964° N, 8.5167° E',
    serial: 'AGF-KAN-004-2026',
    status: 'live',
    roi: { min: 19, max: 24 },
    target: 80000,
    raised: 64000,
    investors: 31,
    cycle: 'Q3 2026',
    iot: true,
    kyc: true,
    featured: false,
    nftId: '#004',
    color: 'green',
    mapColor: 'rgba(0,255,135',
    description: 'Large commercial soybean estate in Kano. 120 hectares fully certified with IoT soil moisture monitoring and automated irrigation.'
  },
  {
    id: 'AGF-DEL-005',
    name: 'Rice Paddies',
    location: 'Delta State',
    state: 'Delta',
    crop: 'Rice',
    size: 35,
    coords: '5.7059° N, 5.9585° E',
    serial: 'AGF-DEL-005-2026',
    status: 'filling',
    roi: { min: 25, max: 30 },
    target: 28000,
    raised: 25480,
    investors: 16,
    cycle: 'Q2 2026',
    iot: true,
    kyc: true,
    featured: false,
    nftId: '#005',
    color: 'gold',
    mapColor: 'rgba(240,192,64',
    description: 'Premium rice cultivation in the Niger Delta region. 35 hectares, harvest imminent. High-demand crop with confirmed offtake agreements.'
  },
  {
    id: 'AGF-ONS-006',
    name: 'Yam Farm',
    location: 'Ondo State',
    state: 'Ondo',
    crop: 'Yam',
    size: 45,
    coords: '7.0945° N, 4.7562° E',
    serial: 'AGF-ONS-006-2026',
    status: 'soon',
    roi: { min: 22, max: 28 },
    target: 42000,
    raised: 0,
    investors: 0,
    cycle: 'Q1 2027',
    iot: false,
    kyc: false,
    featured: false,
    nftId: '#006',
    color: 'muted',
    mapColor: 'rgba(150,150,255',
    description: 'Premium yam cultivation in Ondo State. Site survey completed. KYC pending. Early whitelist investors receive priority allocation.'
  },
  {
    id: 'AGF-SOK-007',
    name: 'Groundnut Farm',
    location: 'Sokoto State',
    state: 'Sokoto',
    crop: 'Groundnut',
    size: 60,
    coords: '13.0059° N, 5.2476° E',
    serial: 'AGF-SOK-007-2026',
    status: 'live',
    roi: { min: 17, max: 23 },
    target: 55000,
    raised: 38500,
    investors: 22,
    cycle: 'Q4 2026',
    iot: true,
    kyc: true,
    featured: false,
    nftId: '#007',
    color: 'green',
    mapColor: 'rgba(0,255,135',
    description: 'Commercial groundnut cultivation in Nigeria\'s groundnut belt. 60 hectares, full IoT deployment. Offtake partner secured.'
  },
  {
    id: 'AGF-ANM-008',
    name: 'Tomato Farm',
    location: 'Anambra State',
    state: 'Anambra',
    crop: 'Tomato',
    size: 20,
    coords: '6.2102° N, 7.0668° E',
    serial: 'AGF-ANM-008-2026',
    status: 'soon',
    roi: { min: 28, max: 35 },
    target: 22000,
    raised: 0,
    investors: 0,
    cycle: 'Q2 2027',
    iot: false,
    kyc: false,
    featured: false,
    nftId: '#008',
    color: 'muted',
    mapColor: 'rgba(150,150,255',
    description: 'High-yield tomato cultivation in Anambra State. Highest projected ROI on platform. KYC verification scheduled for May 2026.'
  }
];

// Farmer demo portfolio (shown when wallet connected in farmer mode)
const FARMER_PORTFOLIO = {
  totalRaised: 94000,
  activeInvestors: 34,
  upcomingPayout: 6800,
  agfiEarned: 4850,
  farms: ['AGF-OGN-001', 'AGF-KEB-002'],
  payouts: [
    { farm: 'Maize Farm. Ogun', investors: 18, amount: 3600, due: '15 Apr 2026', status: 'upcoming' },
    { farm: 'Rice Farm. Kebbi',  investors: 16, amount: 3200, due: '27 Apr 2026', status: 'upcoming' },
    { farm: 'Maize Farm. Ogun', investors: 18, amount: 3300, due: '15 Jan 2026', status: 'paid' },
  ]
};

// Investor demo portfolio
const INVESTOR_PORTFOLIO = {
  value: 15240,
  invested: 12500,
  yieldEarned: 2740,
  avgApy: 22.4,
  investments: [
    { farmId: 'AGF-OGN-001', invested: 3000,  apy: 22, earned: 660,  duration: '12mo', status: 'active',       nft: '#001' },
    { farmId: 'AGF-DEL-005', invested: 6000,  apy: 25, earned: 1500, duration: '12mo', status: 'harvest-soon', nft: '#005' },
    { farmId: 'AGF-KAN-004', invested: 3500,  apy: 19, earned: 665,  duration: '18mo', status: 'active',       nft: '#004' },
  ],
  activity: [
    { type: 'yield',  title: 'Yield Payout',         desc: '$275 from Maize Farm. Ogun',              time: '2 hrs ago',   tx: '5xKj...3mNp' },
    { type: 'invest', title: 'Investment Deposited',  desc: '0.8 SOL into Rice Paddies. Delta',        time: '3 days ago',  tx: '9aQr...7vBk' },
    { type: 'nft',    title: 'Farm NFT Acquired',     desc: 'NFT #001 (Maize Farm. Ogun) minted',      time: '14 days ago', tx: '3eWs...1xLm' },
    { type: 'alert',  title: 'IoT Alert',             desc: 'Kano Soybean: Soil moisture optimal',       time: 'Yesterday',   tx: null },
  ],
  history: [
    { farmId: 'AGF-OGN-001', tx: '5xKj...3mNp', amount: 3000, apy: 22, date: '14 Mar 2026', estReturn: 3660, status: 'active' },
    { farmId: 'AGF-DEL-005', tx: '9aQr...7vBk', amount: 6000, apy: 25, date: '28 Feb 2026', estReturn: 7500, status: 'harvest-soon' },
    { farmId: 'AGF-KAN-004', tx: '3eWs...1xLm', amount: 3500, apy: 19, date: '10 Jan 2026', estReturn: 4165, status: 'active' },
  ],
  yieldReceipts: [
    { farm: 'Maize Farm. Ogun Q1',  tx: 'f011...8c4e', amount: 275.00,  date: '1 Apr 2026' },
    { farm: 'Rice Paddies. Delta Q4', tx: '8a3c...c19d', amount: 375.00,  date: '15 Jan 2026' },
  ]
};

// Helper: get farm by id
function getFarm(id) { return FARMS.find(f => f.id === id); }
function getFeaturedFarms() { return FARMS.filter(f => f.featured); }
function getAllFarms() { return FARMS; }
function formatSOL(usd) { return (usd / 150).toFixed(2); } // rough SOL estimate
function formatAddr(addr) { if(!addr) return ''; return addr.slice(0,4)+'...'+addr.slice(-4); }
function pct(raised, target) { return Math.round((raised/target)*100); }
